<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.11.2 on win32)" generated="20240204 15:06:56.590" rpa="false">
<suite id="s1" name="Untitled" source="C:\Users\mohamed.ali\Desktop\Task\untitled">
<suite id="s1-s1" name="Test" source="C:\Users\mohamed.ali\Desktop\Task\untitled\test">
<suite id="s1-s1-s1" name="Voucher" source="C:\Users\mohamed.ali\Desktop\Task\untitled\test\voucher.robot">
<test id="s1-s1-s1-t1" name="Open Application Voucher Interact">
<kw name="Open Application" library="AppiumLibrary">
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<arguments>
<arg>${remote_url}</arg>
<arg>app=${APP_PATH}</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>platformVersion=${ANDROID_PLATFORM_VERSION}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>appPackage=${APP_PACKAGE}</arg>
<arg>appActivity=${APP_ACTIVITY}</arg>
<arg>autoGrantPermissions=${autoGrantPermissions}</arg>
<arg>noReset=${noReset}</arg>
</arguments>
<msg timestamp="20240204 15:06:56.945" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000138156BBC90&gt;: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context')': /wd/hub/session</msg>
<msg timestamp="20240204 15:06:56.947" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000013811F7E410&gt;: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context')': /wd/hub/session</msg>
<msg timestamp="20240204 15:06:56.948" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000013811F7DB90&gt;: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context')': /wd/hub/session</msg>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20240204 15:06:56.954" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20240204 15:06:56.949" endtime="20240204 15:06:56.954"></status>
</kw>
<msg timestamp="20240204 15:06:56.955" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20240204 15:06:56.968" level="FAIL">MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000013811F87090&gt;: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))</msg>
<status status="FAIL" starttime="20240204 15:06:56.924" endtime="20240204 15:06:56.968"></status>
</kw>
<doc>Test the Voucher functionality</doc>
<tags>
<tag>smoke</tag>
</tags>
<status status="FAIL" starttime="20240204 15:06:56.923" endtime="20240204 15:06:56.969" critical="yes">MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000013811F87090&gt;: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))</status>
</test>
<status status="FAIL" starttime="20240204 15:06:56.624" endtime="20240204 15:06:56.970"></status>
</suite>
<status status="FAIL" starttime="20240204 15:06:56.623" endtime="20240204 15:06:56.972"></status>
</suite>
<status status="FAIL" starttime="20240204 15:06:56.591" endtime="20240204 15:06:56.973"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1">smoke</stat>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Untitled">Untitled</stat>
<stat pass="0" fail="1" id="s1-s1" name="Test">Untitled.Test</stat>
<stat pass="0" fail="1" id="s1-s1-s1" name="Voucher">Untitled.Test.Voucher</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20240204 15:06:56.945" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000138156BBC90&gt;: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context')': /wd/hub/session</msg>
<msg timestamp="20240204 15:06:56.947" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000013811F7E410&gt;: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context')': /wd/hub/session</msg>
<msg timestamp="20240204 15:06:56.948" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000013811F7DB90&gt;: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context')': /wd/hub/session</msg>
<msg timestamp="20240204 15:06:56.955" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
